"""
Phantom Compliance — Signed Audit Logs
Every critical event is chained with HMAC-SHA256 hashes.
Not blockchain-for-vibes. Real tamper-evidence with keyed hashing.
"""

import hmac
import hashlib
import json
import time
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger("phantom_compliance.signed_logs")

# The signing key is derived from the DPAPI-protected master key
# so it cannot be re-generated by an attacker with filesystem access
SIGNING_KEY_CONTEXT = b"phantom_compliance_signed_logs_v1"


def _get_signing_key() -> bytes:
    """Get the HMAC signing key from Credential Manager or machine-derived."""
    from auth.credential_manager import get_password, store_password
    import secrets
    stored_key = get_password("signing_key")
    if stored_key:
        return stored_key.encode("utf-8")
    # Generate and store a new signing key in Windows Credential Manager
    new_key = secrets.token_hex(32)
    store_password("signing_key", new_key)
    return new_key.encode("utf-8")


def sign_entry(entry_data: dict, previous_hash: str = "") -> dict:
    """
    Sign an audit log entry with HMAC-SHA256.
    The entry is serialized, hashed with the previous entry's hash,
    and the result is stored as the entry's hash field.
    """
    key = _get_signing_key()
    entry = dict(entry_data)
    entry["timestamp"] = entry.get("timestamp", datetime.utcnow().isoformat())
    entry["previous_hash"] = previous_hash

    # Serialize deterministically
    serialized = json.dumps(entry, sort_keys=True, ensure_ascii=False, default=str).encode("utf-8")
    entry_hash = hmac.new(key, serialized, hashlib.sha256).hexdigest()
    entry["hash"] = entry_hash
    return entry


def verify_chain(entries: list[dict]) -> tuple[bool, list[str]]:
    """
    Verify the integrity of a chain of signed log entries.
    Returns (is_valid, list_of_errors).
    """
    key = _get_signing_key()
    errors = []
    previous_hash = ""

    for i, entry in enumerate(entries):
        stored_hash = entry.get("hash", "")
        entry_copy = dict(entry)
        entry_copy.pop("hash", None)

        serialized = json.dumps(entry_copy, sort_keys=True, ensure_ascii=False, default=str).encode("utf-8")
        expected_hash = hmac.new(key, serialized, hashlib.sha256).hexdigest()

        if stored_hash != expected_hash:
            errors.append(f"Entry {i}: hash mismatch (tampered)")
            continue

        if entry_copy.get("previous_hash", "") != previous_hash:
            errors.append(f"Entry {i}: chain break (previous_hash mismatch)")
            continue

        previous_hash = stored_hash

    return len(errors) == 0, errors


def log_signed_event(event_type: str, user: str, details: dict,
                     entity_type: str = "", entity_id: int = 0) -> dict:
    """
    Create a signed log entry and store it in the signed_audit_log table.
    Returns the entry dict.
    """
    from utils.database import get_connection

    conn = get_connection()
    last_row = conn.execute(
        "SELECT entry_hash FROM signed_audit_log ORDER BY id DESC LIMIT 1"
    ).fetchone()
    previous_hash = last_row["entry_hash"] if last_row else ""

    entry_data = {
        "event_type": event_type,
        "user": user,
        "details": details,
        "entity_type": entity_type,
        "entity_id": entity_id,
    }

    signed = sign_entry(entry_data, previous_hash)

    conn.execute(
        "INSERT INTO signed_audit_log (event_type, user, details, entity_type, entity_id, "
        "entry_hash, previous_hash, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (
            signed["event_type"], signed["user"],
            json.dumps(signed.get("details", {})),
            signed.get("entity_type", ""), signed.get("entity_id", 0),
            signed["hash"], signed["previous_hash"],
            signed["timestamp"],
        ),
    )
    conn.commit()
    conn.close()

    logger.info(f"Signed audit log: {event_type} by {user} -> hash={signed['hash'][:16]}...")
    return signed


def get_signed_logs(limit: int = 100) -> list[dict]:
    from utils.database import get_connection
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM signed_audit_log ORDER BY id DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def verify_signed_logs() -> dict:
    """Verify the entire signed audit log chain. Returns verification result."""
    from utils.database import get_connection
    conn = get_connection()
    rows = conn.execute("SELECT * FROM signed_audit_log ORDER BY id ASC").fetchall()
    conn.close()
    entries = []
    for r in rows:
        d = dict(r)
        d["details"] = json.loads(d.get("details", "{}"))
        entries.append(d)

    valid, errors = verify_chain(entries)
    return {
        "valid": valid,
        "errors": errors,
        "total_entries": len(entries),
        "verified_entries": len(entries) - len(errors),
    }


def ensure_signed_logs_table():
    from utils.database import get_connection
    conn = get_connection()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS signed_audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            event_type TEXT NOT NULL,
            user TEXT NOT NULL,
            details TEXT DEFAULT '{}',
            entity_type TEXT DEFAULT '',
            entity_id INTEGER DEFAULT 0,
            entry_hash TEXT NOT NULL UNIQUE,
            previous_hash TEXT DEFAULT '',
            timestamp TEXT NOT NULL,
            created_at TEXT DEFAULT (datetime('now'))
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_signed_log_hash ON signed_audit_log(entry_hash)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_signed_log_event ON signed_audit_log(event_type)")
    conn.commit()
    conn.close()
